"""empty message

Revision ID: eacce916a060
Revises: b5a043db7ae4
Create Date: 2026-04-18 20:34:04.244901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eacce916a060'
down_revision: Union[str, Sequence[str], None] = 'b5a043db7ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('authors')
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_articles_author_id'), table_name='articles')
    op.create_index(op.f('ix_articles_user_id'), 'articles', ['user_id'], unique=False)
    op.drop_constraint(op.f('articles_author_id_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_author_id_fkey'), 'articles', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_articles_user_id'), table_name='articles')
    op.create_index(op.f('ix_articles_author_id'), 'articles', ['author_id'], unique=False)
    op.drop_column('articles', 'user_id')
    op.create_table('authors',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('authors_pkey')),
    sa.UniqueConstraint('email', name=op.f('authors_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
