"""empty message

Revision ID: b5a043db7ae4
Revises: 90baf730a6d8
Create Date: 2026-04-16 22:58:36.304462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a043db7ae4'
down_revision: Union[str, Sequence[str], None] = '90baf730a6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('authors', sa.Column('email', sa.String(), nullable=False))
    op.add_column('authors', sa.Column('hashed_password', sa.LargeBinary(), nullable=False))
    op.add_column('authors', sa.Column('role', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'authors', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'role')
    op.drop_column('authors', 'hashed_password')
    op.drop_column('authors', 'email')
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
